### ISSUE TITLE
Toggles don't work in mailPanel

### ISSUE THREAD

**Issue by martinkryl** [romanmatyus/FileMailer#4]
Thanks for a great plugin, I just experienced a strange behaviour - in the mail panel, none of the toggles work. I am running Nette 2.3.2 and Tracy 2.3.2. Please do you have any idea why might that be?

**Comment by romanmatyus** [comment]
Hello, I test it ;)

Dňa 8. mája 2015 9:46:15 CEST používateľ Martin Kryl <notifications@github.com> napísal:
>Thanks for a great plugin, I just experienced a strange behaviour - in
>the mail panel, none of the toggles work. I am running Nette 2.3.2 and
>Tracy 2.3.2. Please do you have any idea why might that be?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/romanmatyus/FileMailer/issues/4

-- 
Odesláno z mého telefonu s Androidem pomocí pošty K-9 Mail. Omluvte prosím moji stručnost.

**Comment by romanmatyus** [comment]
I updated addon to new version for newer Nette. Please, test it;)

**Comment by martinkryl** [comment]
Thanks a lot for this quick update. I can't test it as it seems that the panel can not access the FileMailer (on line 83 it needs it to get the temp dir). I can't get pass this error. The mailer works fine (the mails are saved to the temp dir).

My config is:
```
services:
    nette.mailer:
        class: RM\FileMailer
        setup:
            - $tempDir(%appDir%/../temp/mails)
    mailPanel:
        class: RM\MailPanel
        setup:
            - $newMessageTime(-5 seconds)
            - $show( [subject,from,to,bc,bcc] )
            - $hideEmpty(FALSE)
```

and 

```
nette:
  debugger:
        bar:
            - @mailPanel
```

In my base presenter, I create a service by:

```
$this->mailer = $this->context->getService('nette.mailer');
```
